### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by luttyfrutty** [pilight/windows-phone-gui#1]
Hi,

I'm missing some classed. When I try to build the project it failes because the following files are missing:

GlobalLoading.cs
MainPage.xaml.cs

Can you add them?

Thanks!

Luttyfrutty

**Comment by rdeveen** [comment]
I've added the files. 
The Windows Phone GUI is build for Pilight version 5.0 (i think) It should be updated to at least version 6.0.
